
# Site settings
title: Xu Wei
name: Xu Wei
subtitle: Personal Website
email: songwei20210114@gmail.com
description: >
  Computational Linguist
baseurl: ""
url: ""
github_username:  xuwei-song
disqus_baseurl: "https://xuwei.github.io/"
disqus_shortname: disqus_cxK6oofp6F
permalink: :title

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yuwei Wan"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: xuwei
    url: https://github.com/xuwei-song
    desc: 
    share: false
