
# Site settings
title: Yuwei Wan
name: Yuwei Wan
subtitle: Personal Website
email: ywan10@jhu.edu
description: >
  Computational Linguist
baseurl: ""
url: "https://yuweiwan.github.io/"
github_username:  yuweiwan
disqus_baseurl: "https://yuweiwan.github.io/"
disqus_shortname: https-yuweiwan-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Yuwei Wan"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: yuweiwan
    url: https://github.com/yuweiwan
    desc: 
    share: false

  - name: Linkedin
    icon: linkedin
    username: Yuwei Wan
    url: www.linkedin.com/in/yuweiwan
    desc: Connect with me on Linkedin
    share: true
